package com.cobblemania.economia.gui;

public enum MenuKind {
	ADMIN_MAIN,
	ECONOMY_ACTION,
	ECONOMY_PLAYER_SELECT,
	ECONOMY_AMOUNT,
	MISSIONS_CONFIG,
	MISSIONS_LIST,
	MISSIONS_VIEW,
	AFK_CONFIG,
	SHOP_VIEW,
	SHOP_CONFIG,
	SHOP_PRICE,
	SHOP_SELL,
	SHOP_DURATION,
	RANKS_MAIN,
	RANK_MEMBERS,
	NPC_CONFIG,
	SHOP_NPC_CONFIG,
	PLAYER_LIST,
	PLAYER_DETAIL,
	PLAYER_MENU
}
